name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update system and install dependencies
      run: |
        sudo apt-get update
        sudo apt full-upgrade -y
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libjansson-dev automake autotools-dev build-essential libmpfr-dev binutils linux-libc-dev linux-libc-dev-arm64-cross linux-libc-dev-armel-cross linux-libc-dev-armhf-cross libgmp3-dev libmpc-dev gcc-arm-linux-gnueabihf software-properties-common git nano cmake wget curl lsb-release wget software-properties-common gnupg
        sudo add-apt-repository ppa:ubuntu-toolchain-r/ppa -y
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        sudo apt-get update
        sudo apt install -y gcc-9 g++-9 gcc-10 g++-10 gcc-11 g++-11 g++-12 gcc-12 gcc-13 g++-13
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100 --slave /usr/bin/g++ g++ /usr/bin/g++-13 --slave /usr/bin/gcov gcov /usr/bin/gcov-13
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 90 --slave /usr/bin/g++ g++ /usr/bin/g++-12 --slave /usr/bin/gcov gcov /usr/bin/gcov-12
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 80 --slave /usr/bin/g++ g++ /usr/bin/g++-11 --slave /usr/bin/gcov gcov /usr/bin/gcov-11
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 60 --slave /usr/bin/g++ g++ /usr/bin/g++-10 --slave /usr/bin/gcov gcov /usr/bin/gcov-10
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 40 --slave /usr/bin/g++ g++ /usr/bin/g++-9 --slave /usr/bin/gcov gcov /usr/bin/gcov-9
        export PATH=$PATH:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin

    - name: Download and install LLVM
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 16
        sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-16 100
        sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-16 100
        sudo update-alternatives --config cc

    - name: Set up OpenSSL
      run: |
        mkdir $HOME/opt && cd $HOME/opt
        wget https://www.openssl.org/source/openssl-1.1.1o.tar.gz
        tar -zxvf openssl-1.1.1o.tar.gz
        cd openssl-1.1.1o
        ./config && make && make test
        mkdir $HOME/opt/lib
        mv $HOME/opt/openssl-1.1.1o/libcrypto.so.1.1 /opt/lib/
        mv $HOME/opt/openssl-1.1.1o/libssl.so.1.1 /opt/lib/
        export LD_LIBRARY_PATH=/opt/lib:$LD_LIBRARY_PATH

    - name: Clone repository
      run: git clone https://github.com/simeononsecurity/CCminer-ARM-optimized.git
      
    - name: Navigate to repository directory
      run: cd CCminer-ARM-optimized
      
    - name: Make scripts executable
      run: |
        chmod +x build.sh
        chmod +x configure.sh
        chmod +x autogen.sh
    - name: Build CCminer with clang++
      run: CXX=clang++ CC=clang ./build.sh
