name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update system and install dependencies
      run: |
        sudo apt-get update
        sudo apt full-upgrade -y
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libjansson-dev automake autotools-dev build-essential

    - uses: actions/checkout@v2
    - name: Download and install LLVM
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh all

    - name: Clone repository
      run: git clone https://github.com/Oink70/CCminer-ARM-optimized.git
    - name: Navigate to repository directory
      run: cd CCminer-ARM-optimized
    - name: Make scripts executable
      run: |
        chmod +x build.sh
        chmod +x configure.sh
        chmod +x autogen.sh
    - name: Build CCminer with clang++
      run: CXX=clang++ CC=clang ./build.sh
